GakuenMVC/Controllers/HomeController.cs
using System.Net;
using System.Web.Mvc;
using DLLGakuen;
using DLLGakuen.Entity;

namespace GakuenMVC.Controllers
{
    [RequireHttps]
    public class HomeController : Controller
    {
        private readonly IServiceGateway<NewsMessage> _newsMessageServiceGateway =
            new DllFacade().GetNewsMessageServiceGateway();
        public ActionResult Index()
        {
            return View(_newsMessageServiceGateway.Read());
        }
        [Authorize(Users = "isAdmin")]
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
        
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

GakuenMVC/Controllers/NewsMessagesController.cs
using System.Net;
using System.Web.Mvc;
using DLLGakuen;
using DLLGakuen.Entity;

namespace GakuenMVC.Controllers
{
    public class NewsMessagesController : Controller
    {
        private readonly IServiceGateway<NewsMessage> _newsMessageServiceGateway =
            new DllFacade().GetNewsMessageServiceGateway();
        private readonly IServiceGateway<ImageToHost> _imageToHostServiceGateway = new DllFacade().GetImageTohostServiceGateway();
        private readonly IServiceGateway<VideoToHost> _videoToHostServiceGateway = new DllFacade().GetVideoToHostServiceGateway();

        // GET: NewsMessages
        public ActionResult Index()
        {
            return View(_newsMessageServiceGateway.Read());
        }

        // GET: NewsMessages/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewsMessage newsMessage = _newsMessageServiceGateway.Read(id.Value);
            if (newsMessage == null)
            {
                return HttpNotFound();
            }
            return View(newsMessage);
        }

        // GET: NewsMessages/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NewsMessages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Body")] NewsMessage newsMessage,[Bind(Include = "Id,ImagePath")] ImageToHost imageToHost, [Bind(Include = "Id,VideoPath")] VideoToHost videoToHost)
        {
            if (ModelState.IsValid)
            {
               var news =  newsMessage;

                news.ImageToHost = imageToHost;
                news.VideoToHost = videoToHost;
                
                _newsMessageServiceGateway.Create(news);
                return RedirectToAction("Index");
            }

            return View(newsMessage);
        }

        // GET: NewsMessages/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewsMessage newsMessage = _newsMessageServiceGateway.Read(id.Value);
            if (newsMessage == null)
            {
                return HttpNotFound();
            }
            return View(newsMessage);
        }

        // POST: NewsMessages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Body,ImageToHost,VideoToHost")] NewsMessage newsMessage)
        {
            if (ModelState.IsValid)
            {
                _newsMessageServiceGateway.Update(newsMessage);
                _imageToHostServiceGateway.Update(newsMessage.ImageToHost);
                _videoToHostServiceGateway.Update(newsMessage.VideoToHost);
                return RedirectToAction("Index");
            }
            return View(newsMessage);
        }

        // GET: NewsMessages/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewsMessage newsMessage = _newsMessageServiceGateway.Read(id.Value);
            if (newsMessage == null)
            {
                return HttpNotFound();
            }
            return View(newsMessage);
        }

        // POST: NewsMessages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var news = _newsMessageServiceGateway.Read(id);
            _newsMessageServiceGateway.Delete(id);
            if (news.ImageToHost != null)
            {
                
                _imageToHostServiceGateway.Delete(news.ImageToHost.Id);
            }
            if (news.VideoToHost != null)
            {
                _videoToHostServiceGateway.Delete(news.VideoToHost.Id);
            }
            return RedirectToAction("Index");
        }


        // GET: NewsMessages/NewsFeed/5
        public ActionResult NewsFeed(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewsMessage news = _newsMessageServiceGateway.Read(id.Value);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }
    }
}

GakuenMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<head>
    @Styles.Render("~/Content/HomePage.css")
</head>
<body>
    <h2>@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</body>

GakuenMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<body>
            <h2>@ViewBag.Title.</h2>
            <h3>@ViewBag.Message</h3>

            <address>
                One Microsoft Way<br />
                Redmond, WA 98052-6399<br />
                <abbr title="Phone">P:</abbr>
                425.555.0100
            </address>

            <address>
                <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
                <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
            </address>
  
</body>

GakuenMVC/Views/Home/Index.cshtml
@using DLLGakuen.Entity
@using System.Linq;
@model IEnumerable<DLLGakuen.Entity.NewsMessage>
@{
    ViewBag.Title = "Home Page";
}
@Scripts.Render("~/Scripts/slideshow.js")

<body>

    @section slideshow{
        @{
            int p = 0;
        }
        <div id="header" class="slide img-rounded">
            @foreach (var x in Model.OrderBy(x => x.Id).Reverse().Take(Model.Count()))
            {
                <a href="@Url.Action("NewsFeed", "NewsMessages", new {id = x.Id})" class="mySlides">

                    <div style=display: inline-block class="img-rounded">
                        <img src="@Html.DisplayFor(modelItem => x.ImageToHost.ImagePath)" class="img-rounded" width="30%" height="300" />
                    </div>
                    <span id="slidewrap" class="img-rounded">

                        <b>@Html.DisplayFor(modelItem => x.Title)</b>
                        <br />
                        @Html.DisplayFor(modelItem => x.Body)

                    </span>
                </a>
                if (++p == 3)
                {
                    break;
                }
            }
            <a id="left" class="img-rounded noselect" onclick="plusDivs(-1)">
                <p><<</p>
            </a>
            <a id="right" class="img-rounded noselect" onclick="plusDivs(+1)"><p>>></p></a>
        </div>
    }

    <br />
    @foreach (var item in Model.Reverse())
            {
        <div class="col-md-4">

            <div class="divimg img-rounded">
                <a href="@Url.Action("NewsFeed","NewsMessages", new {id = item.Id})" class="divimg img-rounded">
                    <img src="@Html.DisplayFor(modelItem => item.ImageToHost.ImagePath)" class="divimg img-rounded" />
                    <span id="wrapper" class="divimg img-rounded">
                        <p style="font-size: 125%; text-align: center;">
                            <b>@Html.DisplayFor(modelItem => item.Title)</b>
                            <br />
                            @Html.DisplayFor(modelItem => item.Body)
                        </p>
                    </span>
                </a>
            </div>
        </div>
    }
    <div class="row"></div>
</body>