GakuenMVC/Controllers/SchedulesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DLLGakuen;
using DLLGakuen.Entity;
using GakuenMVC.Models;

namespace GakuenMVC.Controllers
{
    public class SchedulesController : Controller
    {
        private readonly IServiceGateway<Schedule> _scheduleServiceGateway = new DllFacade().GetScheduleServiceGateway();

        // GET: Schedules
        public ActionResult Index()
        {
            return View(_scheduleServiceGateway.Read());
        }

        // GET: Schedules/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Schedule schedule = _scheduleServiceGateway.Read(id.Value);
            if (schedule == null)
            {
                return HttpNotFound();
            }
            return View(schedule);
        }

        // GET: Schedules/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Schedules/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Day")] Schedule schedule)
        {
            if (ModelState.IsValid)
            {
                _scheduleServiceGateway.Create(schedule);
                return RedirectToAction("Index");
            }

            return View(schedule);
        }

        // GET: Schedules/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Schedule schedule = _scheduleServiceGateway.Read(id.Value);
            if (schedule == null)
            {
                return HttpNotFound();
            }
            return View(schedule);
        }

        // POST: Schedules/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Day")] Schedule schedule)
        {
            if (ModelState.IsValid)
            {
                _scheduleServiceGateway.Update(schedule);
                return RedirectToAction("Index");
            }
            return View(schedule);
        }

        // GET: Schedules/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Schedule schedule = _scheduleServiceGateway.Read(id.Value);
            if (schedule == null)
            {
                return HttpNotFound();
            }
            return View(schedule);
        }

        // POST: Schedules/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _scheduleServiceGateway.Delete(id);
            return RedirectToAction("Index");
        }

        public ActionResult OverView()
        {
            return View(_scheduleServiceGateway.Read());
        }

        public ActionResult SchoolEventsInSchedule(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Schedule schedule = _scheduleServiceGateway.Read(id.Value);
            if (schedule == null)
            {
                return HttpNotFound();
            }
            return View(schedule);
        }
    }
}

GakuenMVC/Controllers/SchoolEventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DLLGakuen;
using DLLGakuen.Entity;
using GakuenMVC.Models;

namespace GakuenMVC.Controllers
{
    public class SchoolEventsController : Controller
    {
        private readonly IServiceGateway<SchoolEvent> _schoolEventserviceGateway =
            new DllFacade().GetSchoolEventServiceGateway();

        // GET: SchoolEvents
        public ActionResult Index()
        {
            return View(_schoolEventserviceGateway.Read());
        }

        // GET: SchoolEvents/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SchoolEvent schoolEvent = _schoolEventserviceGateway.Read(id.Value);
            if (schoolEvent == null)
            {
                return HttpNotFound();
            }
            return View(schoolEvent);
        }

        // GET: SchoolEvents/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SchoolEvents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Minuttes,Name")] SchoolEvent schoolEvent)
        {
            if (ModelState.IsValid)
            {
                _schoolEventserviceGateway.Create(schoolEvent);
                return RedirectToAction("Index");
            }

            return View(schoolEvent);
        }

        // GET: SchoolEvents/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SchoolEvent schoolEvent = _schoolEventserviceGateway.Read(id.Value);
            if (schoolEvent == null)
            {
                return HttpNotFound();
            }
            return View(schoolEvent);
        }

        // POST: SchoolEvents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Minuttes,Name")] SchoolEvent schoolEvent)
        {
            if (ModelState.IsValid)
            {
                _schoolEventserviceGateway.Update(schoolEvent);
                return RedirectToAction("Index");
            }
            return View(schoolEvent);
        }

        // GET: SchoolEvents/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SchoolEvent schoolEvent = _schoolEventserviceGateway.Read(id.Value);
            if (schoolEvent == null)
            {
                return HttpNotFound();
            }
            return View(schoolEvent);
        }

        // POST: SchoolEvents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _schoolEventserviceGateway.Delete(id);

            return RedirectToAction("Index");
        }

        public ActionResult SchoolEventDetail(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SchoolEvent schoolEvent = _schoolEventserviceGateway.Read(id.Value);
            if (schoolEvent == null)
            {
                return HttpNotFound();
            }
            return View(schoolEvent);
        }
    }
}

GakuenMVC/Views/SchoolEvents/Create.cshtml
@model DLLGakuen.Entity.SchoolEvent

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SchoolEvent</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Minuttes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Minuttes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Minuttes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GakuenMVC/Views/SchoolEvents/Delete.cshtml
@model DLLGakuen.Entity.SchoolEvent

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SchoolEvent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Minuttes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Minuttes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GakuenMVC/Views/SchoolEvents/Details.cshtml
@model DLLGakuen.Entity.SchoolEvent

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SchoolEvent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Minuttes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Minuttes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

GakuenMVC/Views/SchoolEvents/Edit.cshtml
@model DLLGakuen.Entity.SchoolEvent

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SchoolEvent</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Minuttes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Minuttes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Minuttes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GakuenMVC/Views/SchoolEvents/Index.cshtml
@model IEnumerable<DLLGakuen.Entity.SchoolEvent>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Minuttes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Minuttes)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

GakuenMVC/Views/SchoolEvents/SchoolEventDetail.cshtml
@model DLLGakuen.Entity.SchoolEvent

@{
    ViewBag.Title = "SchoolEventDetail";
}

<h2>Oversigt over Event: @Model.Name</h2>

<body>
<div style="display: table-row">
    <div class="jumbotron" style="width: 400px; display: table-cell; border: 2px solid midnightblue; border-radius: 3px">
        <p>@Html.Label("Event: ")</p>
        <p id="magic">@Html.DisplayFor(model => model.Name)</p>
        <p>@Html.Label("Tid i Min: ")</p>
        <p>@Html.DisplayFor(model => model.Minuttes)</p>
        <p>@Html.Label("Dag: ")</p>
        <p>@Html.DisplayFor(model => model.Schedule.Day)</p>
    </div>

    <div class="jumbotron" style="display: table-cell; border: 2px solid midnightblue">
        <p>@Html.Label("Deltager: ")</p>
        <p>@Html.DisplayFor(model => model.Users)</p>
    </div>
</div>

    <div>
        <div style="margin-top: 30px" class="col-md-2">
            <button type="button" class="btn btnbtn-sm" style="background-color: #ff0000;">
                @Html.ActionLink("Tilbage", "SchoolEventsInSchedule","Schedules", new { id = Model.Schedule.Id} , new { style = "color: white" })
            </button>
        </div>
    </div>
</body>